#ifndef FERRIS_SWEEP_TAP_DANCE_H 
#define FERRIS_SWEEP_TAP_DANCE_H

enum {
    AMPERSAND_PIPE,
    ASTERISK_CIRCLE,
    BRACES,
    CURLY_BRACES,
    EQUAL_PLUS,
    GRAVE_TILDE,
    LESSTHAN_GREATERTHAN,
    PARANTHESIS,
    Q_ESCAPE,
    QUESTION_EXCLAMATION,
    QUOTE_DOUBLEQUOTE,
    SEMICOLON_COLON,
    SLASH_BACKSLASH,
    UNDERSCORE_MINUS,
    Z_CAPSLOCK,
};

#endif
